baseurl: https://devblog.kakaostyle.com
title: 카카오스타일 기술 블로그

defaultContentLanguage: ko
defaultContentLanguageInSubdir: true

hasCJKLanguage: true

services:
  googleAnalytics:
    id: G-HBL5QKGKNR

pagination:
  pagerSize: 5

pygmentsuseclasses: true

disqusShortname: croquiscom-devblog

languages:
  en:
    weight: 0
  ko:
    weight: 0

blackfriday:
  smartypants: false

buildFuture: true

ignoreLogs:
  - warning-goldmark-raw-html
